version: '3.7'
services:
  twitter-to-kafka-service:
    image: ${GROUP_ID}/twitter.to.kafka.service:${SERVICE_VERSION:-latest}
    ports:
      - "5005:5005"
    volumes:
      - "./docker-logs:/workspace/twitter-to-kafka-service/logs"
      - "./check-config-server-started.sh:/usr/local/bin/check-config-server-started.sh"
#      #   Here we see that we can simply override any configuration variable, for example, for the bootstrap server
#      #   We use the Kafka-broker-1 from Kafka cluster yml file instead of localhost because we will run *everything inside docker*
#      #   And to be able to reach to Kafka from our service, we should use hostname.
#      #  Because inside docker, all these containers will act as different hosts.
    user: root #To be able to run updates and also install the Curl command in the shell script we will run compose file with the user root.
#    # we will override entry point for the Twitter to Kafka service and set this shell script that we created.
    entrypoint: ["check-config-server-started.sh"]
    depends_on:
      - config-server

    #Springs's interpretation of the ENV. Variables names:
    # in BEAN-NAME_PROPERTY-NAME -> the property name can likewise also refer to another (bean containing another bean);
    #in the properties.xml parlance would be BEAN BEAN-NAME.PROPERTY-NAME
    #and in the properties yml parlance, BEAN-NAME:
    #                                     PROPERTY-NAME: value
    #At the Class level definition of the bean, the BEAN_NAME translates to a class through the use of @ConfigurationProperties(prefix = "x"),
    #so that in the end the values of its corresponding configuration properties
    #(taken from possible several properties sources (like Config Servers, yaml properties files,...)  will be mapped to the bean attributes (instace variables)
    #-> (ie: KAFKA-CONFIG translates to to KafkaConfigData
    # @ConfigurationProperties(prefix = "kafka-config")
    #public class KafkaConfigData
    environment:
      - "JAVA_OPTS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005 -Xms128m -Xmx256m"
      - "LOGGING_LEVEL_COM_MICROSERVICES_DEMO=info"
      - "LOGGING_LEVEL_ROOT=info"
      - "KAFKA-CONFIG_TOPIC-NAME=twitter-topic"
      - "KAFKA-CONFIG_BOOTSTRAP-SERVERS=kafka-broker-1:9092, kafka-broker-2:9092, kafka-broker-3:9092"
      - "KAFKA-CONFIG_SCHEMA-REGISTRY-URL=http://schema-registry:8081"
      - "TWITTER-TO-KAFKA-SERVICE_ENABLE-MOCK-TWEETS=false"
      - "TWITTER-TO-KAFKA-SERVICE_ENABLE-V2-TWEETS=true"
      - "TWITTER-TO-KAFKA-SERVICE_TWITTER-V2-BASE-URL=https://api.twitter.com/2/tweets/search/stream?tweet.fields=created_at&expansions=author_id"
      - "TWITTER-TO-KAFKA-SERVICE_TWITTER-V2-RULES-BASE-URL=https://api.twitter.com/2/tweets/search/stream/rules"
      - "TWITTER-TO-KAFKA-SERVICE_TWITTER-V2-BEARER-TOKEN=${TWITTER_BEARER_TOKEN}"
      #      To be able to reach to Config server, Twitter to Kafka service cannot use localhost anymore.
      #It should use the host name of the config server container.
      - "SPRING_CLOUD_CONFIG_URI=http://config-server:8888" #To be able to reach to Config server,
                    #Twitter to Kafka service cannot use localhost anymore. It should use the host name of the config server container.
      - "ENCRYPT_KEY=Demo_Pwd!2020"
    networks:
      - ${GLOBAL_NETWORK:-services}
  config-server:
    image: ${GROUP_ID}/config.server:${SERVICE_VERSION:-latest}
    ports:
                    #Since we need to reach to config server using localhost, we need to open the 8888 port in the services.yml file
      - "8888:8888" #the port definition for config server and add 8888 to be able to reach to config server using localhost 8888 From the new Kafka to Elastic Service.
      - "5006:5006"
    volumes:
      #In order to not lose the LOG data, preserving its old states after restarting the Container, we use VOLUMES
      #for that there is a mapping between the docker logs folder and the logs folders inside the service,
      - "./docker-logs:/workspace/config-server/logs"
      #The container has its log folder structure
      #And the logs folders local to the module are created using the build image goal of Spring boot
    environment:
      #      in the Java Opts environment variable, set the 5006 port to open a port for remote debugging for this service
      - "JAVA_OPTS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5006 -Xms128m -Xmx256m"
      - "ENCRYPT_KEY=Demo_Pwd!2020"
      #passed encrypt_key environment variable in the environment section because it is required to decrypt the secrets at runtime.
      #both services, twitter to kafka service and config server has the same network definition, so they can see each other.
    networks:
      - ${GLOBAL_NETWORK:-services}
        
        
