#the application.yaml file in the Twitter to Kafka service emptied, otherwise it will overwrite
#the configuration that you defined in the config server repository because I configured overriding
#properties in the config-client.yml file.